# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-30 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('word', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='request_id',
            field=models.IntegerField(default=0),
        ),
    ]
