# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-30 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20191130_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
        migrations.AddField(
            model_name='response',
            name='request_id',
            field=models.IntegerField(default=0),
        ),
    ]
