# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-12-01 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20191130_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='requests',
            field=models.ManyToManyField(to='front.Request'),
        ),
    ]
